
name: sidemo

on:
  push:
    branches: [ "main" ]
    


jobs:
  # This workflow contains a single job called "build" 
  process:
    runs-on: ubuntu-latest
    
    steps:
      - env:
          DATA_VALUE: ${{ github.event.head_commit.message }}
    #   run: echo $DATA_VALUE
        run: echo ${{ github.event.head_commit.message }}




