
name: sidemo

on:
  push:
    branches: [ "main" ]
    
env:
  DATA_VALUE: ${{ secrets.SIDEMO_SECRET }}

jobs:
  # This workflow contains a single job called "build"
  process:
    runs-on: ubuntu-latest
    
    steps:

      # Runs a command using the runners shell
      - run: echo ${{ github.event.head_commit.message }}
      - run: echo ${{ secrets.SIDEMO_SECRET }}



