
name: sidemo

on:
  push:
    branches: [ "main" ]
    


jobs:
  # This workflow contains a single job called "build" 
  process:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.head_commit.message }}
     # - env:
    #      DATA_VALUE: ${{ github.event.head_commit.message }}
    #   run: echo $DATA_VALUE
      




