
name: sidemo

on:
  push:
    branches: [ "main" ]
    


jobs:
  # This workflow contains a single job called "build"
  process:
    runs-on: ubuntu-latest
    
    steps:
      - env:
          DATA_VALUE: ${{ secrets.SIDEMO_SECRET }}
        run: echo $DATA_VALUE:8:20




